package com.dropshipshop.api.refund.domain;

public enum RefundReason {
	CUSTOMER_CANCEL,
	SUPPLIER_OUT_OF_STOCK,
	ADMIN_CANCEL,
	PAYMENT_AMOUNT_MISMATCH,
	LATE_DEPOSIT_EXCEPTION,
	SALE_UNAVAILABLE_AT_DEPOSIT,
	RETURN_REQUESTED,
	EXCHANGE_REQUESTED,
	DELIVERY_GROUP_OUT_OF_STOCK
}
