package com.dropshipshop.api.notification.domain;

public enum NotificationType {
	PAYMENT_PENDING,
	PAYMENT_COMPLETED,
	PAYMENT_EXCEPTION,
	OUT_OF_STOCK,
	SHIPMENT_STARTED,
	DELIVERY_COMPLETED,
	DELIVERY_STATUS_CORRECTED,
	DELAY_NOTICE,
	CLAIM_STATUS_CHANGED,
	REFUND_COMPLETED,
	CUSTOMER_INQUIRY_ANSWERED,
	SUPPLIER_INVITATION,
	SUPPLIER_FULFILLMENT_REQUESTED,
	SUPPLIER_PRODUCT_REVIEW_RESULT,
	SUPPLIER_CLAIM_WORK_REQUESTED,
	MARKETING
}
