package com.dropshipshop.api.notification.domain;

public enum NotificationType {
	PAYMENT_PENDING,
	PAYMENT_COMPLETED,
	PAYMENT_EXCEPTION,
	OUT_OF_STOCK,
	SHIPMENT_STARTED,
	DELIVERY_COMPLETED,
	DELAY_NOTICE,
	CLAIM_STATUS_CHANGED,
	REFUND_COMPLETED,
	CUSTOMER_INQUIRY_ANSWERED,
	MARKETING
}
