package com.dropshipshop.api.payment.domain;

public enum PaymentEventType {
	CONFIRM_REQUESTED,
	CONFIRM_APPROVED,
	CONFIRM_REJECTED,
	PAYMENT_EXCEPTION,
	PAYMENT_EXCEPTION_CANCEL_REQUESTED,
	PAYMENT_EXCEPTION_CANCEL_COMPLETED,
	PAYMENT_EXCEPTION_CANCEL_FAILED,
	TOSS_WEBHOOK_RECEIVED,
	PAYMENT_REVIEW_REQUIRED,
	BANK_TRANSFER_DEPOSIT_CONFIRMED,
	BANK_TRANSFER_UNPAID_CANCELLED,
	BANK_TRANSFER_DEPOSIT_MISMATCH_RECORDED,
	BANK_TRANSFER_LATE_DEPOSIT_RECORDED,
	REFUND_REQUESTED,
	REFUND_COMPLETED,
	MANUAL_REFUND_COMPLETED,
	REFUND_FAILED
}
