package com.dropshipshop.api.payment.domain;

public enum PaymentEventType {
	CONFIRM_REQUESTED,
	CONFIRM_APPROVED,
	CONFIRM_REJECTED,
	PAYMENT_EXCEPTION,
	PAYMENT_EXCEPTION_CANCEL_REQUESTED,
	PAYMENT_EXCEPTION_CANCEL_COMPLETED,
	PAYMENT_EXCEPTION_CANCEL_FAILED,
	TOSS_WEBHOOK_RECEIVED,
	PAYMENT_REVIEW_REQUIRED,
	REFUND_REQUESTED,
	REFUND_COMPLETED,
	REFUND_FAILED
}
