package com.dropshipshop.api.payment.domain;

public enum PaymentEventType {
	CONFIRM_REQUESTED,
	CONFIRM_APPROVED,
	CONFIRM_REJECTED,
	PAYMENT_EXCEPTION,
	REFUND_REQUESTED,
	REFUND_COMPLETED,
	REFUND_FAILED
}
