package com.dropshipshop.api.catalog.domain;

public enum ProductChangeType {
	PRICE,
	PRODUCT_STATUS,
	COMPLIANCE_STATUS,
	PRODUCT_CATEGORY,
	OPTION_STATUS,
	SUPPLIER,
	PRODUCT_BASE,
	ORDER_QUANTITY,
	OPTION_BASE,
	IMAGES,
	DETAIL_BLOCKS,
	NOTICE,
	REVIEW_STATUS,
	PRODUCT_DELETED,
	OPTION_DELETED
}
