package com.dropshipshop.api.common.error;

public enum ApiErrorCode {
	UNAUTHORIZED,
	FORBIDDEN,
	VALIDATION_FAILED,
	MALFORMED_REQUEST,
	BUSINESS_RULE_VIOLATION,
	RESOURCE_NOT_FOUND,
	CONFLICT,
	UPSTREAM_SERVICE_ERROR,
	INTERNAL_SERVER_ERROR
}
