package com.dropshipshop.api.order.domain;

public enum AdminOrderActionType {
	BANK_TRANSFER_DEPOSIT_CONFIRMED,
	BANK_TRANSFER_UNPAID_CANCELLED,
	BANK_TRANSFER_DEPOSIT_MISMATCH_RECORDED,
	MANUAL_REFUND_COMPLETED,
	SUPPLIER_WORK_START,
	SUPPLIER_ORDER_COMPLETED,
	DELAY_NOTICE_SENT,
	OUT_OF_STOCK,
	SHIPMENT_STARTED,
	SHIPMENT_MANUAL_CORRECTION,
	RETURN_RECEIVED,
	RETURN_REFUND_REQUESTED,
	RETURN_REJECTED
}
