package com.dropshipshop.api.claim.domain;

public enum ClaimStatus {
	REQUESTED,
	UNDER_REVIEW,
	EVIDENCE_REQUESTED,
	APPROVED,
	REJECTED,
	RETURN_WAITING,
	RETURN_RECEIVED,
	REFUND_PROCESSING,
	EXCHANGE_SHIPPING,
	COMPLETED,
	WITHDRAWN
}
