package com.dropshipshop.api.policy.domain;

public enum PolicyDocumentType {
	TERMS_OF_SERVICE,
	PRIVACY_POLICY,
	SUPPLIER_APPLICATION_PRIVACY,
	SHIPPING_POLICY,
	CANCELLATION_REFUND_POLICY,
	OUT_OF_STOCK_NOTICE
}
