import type { AdminOrder, AdminProduct, AdminSupplier } from "./admin";

export const adminSuppliers: AdminSupplier[] = [
  { id: "mock-supplier-1", name: "대림건설자재" },
  { id: "mock-supplier-2", name: "현대산업안전" },
  { id: "mock-supplier-3", name: "포스코안전" },
];

export const adminProducts: AdminProduct[] = [
  {
    id: "mock-product-1",
    supplierId: "mock-supplier-1",
    supplierName: "대림건설자재",
    name: "K2 안전모 K2-THINK 1",
    summary: "가볍고 편안한 프리미엄 안전모",
    sourcePrice: 7200,
    basePrice: 7200,
    categoryCode: "PPE_SAFETY_HELMET",
    status: "ACTIVE",
    complianceStatus: "VERIFIED",
    thumbnailImageUrl: null,
    detailVersion: 3,
    sourceUrl: null,
    saleReady: false,
    saleBlockers: ["THUMBNAIL", "ACTIVE_OPTION", "PRODUCT_NOTICE"],
    optionCount: 0,
    hasThumbnail: false,
    hasProductNotice: false,
    hasDetailContent: false,
  },
  {
    id: "mock-product-2",
    supplierId: "mock-supplier-2",
    supplierName: "현대산업안전",
    name: "K2 안전화 K2-67S",
    summary: "현장용 방수 안전화",
    sourcePrice: 48500,
    basePrice: 48500,
    categoryCode: "PPE_SAFETY_SHOES",
    status: "ACTIVE",
    complianceStatus: "VERIFIED",
    thumbnailImageUrl: null,
    detailVersion: 2,
    sourceUrl: null,
    saleReady: false,
    saleBlockers: ["THUMBNAIL", "ACTIVE_OPTION", "PRODUCT_NOTICE"],
    optionCount: 0,
    hasThumbnail: false,
    hasProductNotice: false,
    hasDetailContent: false,
  },
  {
    id: "mock-product-3",
    supplierId: "mock-supplier-3",
    supplierName: "포스코안전",
    name: "반사 형광조끼 SV-1001",
    summary: "야간 작업용 고휘도 조끼",
    sourcePrice: 5800,
    basePrice: 5800,
    categoryCode: "PPE_HIGH_VISIBILITY_VEST",
    status: "SOLD_OUT",
    complianceStatus: "PENDING",
    thumbnailImageUrl: null,
    detailVersion: 4,
    sourceUrl: null,
    saleReady: false,
    saleBlockers: ["THUMBNAIL", "ACTIVE_OPTION", "PRODUCT_NOTICE", "COMPLIANCE"],
    optionCount: 0,
    hasThumbnail: false,
    hasProductNotice: false,
    hasDetailContent: false,
  },
  {
    id: "mock-product-4",
    supplierId: "mock-supplier-1",
    supplierName: "대림건설자재",
    name: "3M 컴포트 그립 장갑 CG-100",
    summary: "정밀 작업용 코팅 장갑",
    sourcePrice: 1650,
    basePrice: 1650,
    categoryCode: "PPE_INSULATED_GLOVES",
    status: "ACTIVE",
    complianceStatus: "VERIFIED",
    thumbnailImageUrl: null,
    detailVersion: 1,
    sourceUrl: null,
    saleReady: false,
    saleBlockers: ["THUMBNAIL", "ACTIVE_OPTION", "PRODUCT_NOTICE"],
    optionCount: 0,
    hasThumbnail: false,
    hasProductNotice: false,
    hasDetailContent: false,
  },
];

export const adminOrders: AdminOrder[] = [
  {
    orderId: "mock-order-1",
    orderNumber: "20240522-000123",
    status: "SUPPLIER_ORDER_PENDING",
    supplierName: "대림건설자재",
    customerEmail: "honggd@safebuild.co.kr",
    checkoutNumber: "CK-20240522-123",
    itemCount: 3,
    totalAmount: 2450000,
    createdAt: "2024-05-22T14:32:00Z",
    items: [
      { productName: "안전모 ABS, 백색", optionName: "SH-1001", quantity: 6, unitPrice: 8000 },
      { productName: "안전화 K2-67", optionName: "SH-2001", quantity: 4, unitPrice: 65000 },
      { productName: "형광조끼", optionName: "SH-3001", quantity: 2, unitPrice: 12000 },
    ],
    shippingAddress: "서울특별시 중구 세종대로 110",
    paymentMethod: "신용카드",
  },
  {
    orderId: "mock-order-2",
    orderNumber: "20240522-000122",
    status: "SHIPPED",
    supplierName: "현대산업안전",
    customerEmail: "order@hyundai-safe.co.kr",
    checkoutNumber: "CK-20240522-122",
    itemCount: 1,
    totalAmount: 1890000,
    createdAt: "2024-05-22T13:11:00Z",
    items: [{ productName: "K2 안전화 K2-67S", optionName: "265mm", quantity: 8, unitPrice: 48500 }],
    shippingAddress: "경기도 성남시 분당구 판교역로 235",
    paymentMethod: "계좌이체",
  },
  {
    orderId: "mock-order-3",
    orderNumber: "20240521-000119",
    status: "OUT_OF_STOCK",
    supplierName: "포스코안전",
    customerEmail: "site@posco-safe.co.kr",
    checkoutNumber: "CK-20240521-119",
    itemCount: 1,
    totalAmount: 4680000,
    createdAt: "2024-05-21T17:03:00Z",
    items: [{ productName: "포스탑 추락방지 세트", optionName: "FS-2020", quantity: 21, unitPrice: 89000 }],
    shippingAddress: "인천광역시 연수구 컨벤시아대로 165",
    paymentMethod: "신용카드",
  },
];
