export const PRODUCT_CATEGORIES = [
  ["개인보호구", "", "PPE_SAFETY_HELMET", "안전모"],
  ["개인보호구", "", "PPE_SAFETY_SHOES", "안전화"],
  ["개인보호구", "", "PPE_FALL_ARREST_HARNESS", "안전대(추락방지용)"],
  ["개인보호구", "", "PPE_SAFETY_BELT", "안전벨트"],
  ["개인보호구", "", "PPE_SAFETY_GLASSES", "보안경"],
  ["개인보호구", "", "PPE_RESPIRATOR", "방진·방독마스크"],
  ["개인보호구", "", "PPE_EAR_PROTECTION", "귀마개·귀덮개"],
  ["개인보호구", "", "PPE_WORK_GLOVES", "일반 작업장갑"],
  ["개인보호구", "", "PPE_INSULATED_GLOVES", "절연장갑"],
  ["개인보호구", "", "PPE_WELDING_GLOVES", "용접장갑"],
  ["개인보호구", "", "PPE_HIGH_VISIBILITY_VEST", "고가시성 안전조끼"],
  ["개인보호구", "", "PPE_PROTECTIVE_CLOTHING", "보호복(유해물질 작업용)"],
  ["추락·낙하 예방시설", "", "FALL_PREVENTION_GUARDRAIL", "안전난간"],
  ["추락·낙하 예방시설", "", "FALL_PREVENTION_NET", "추락방지망"],
  ["추락·낙하 예방시설", "", "FALLING_OBJECT_NET", "낙하물방지망"],
  ["추락·낙하 예방시설", "", "OPENING_COVER", "개구부 덮개"],
  ["추락·낙하 예방시설", "", "WORK_PLATFORM", "작업발판"],
  ["추락·낙하 예방시설", "", "SAFE_PASSAGE", "안전통로"],
  ["추락·낙하 예방시설", "", "LIFELINE", "수직·수평 생명줄"],
  ["추락·낙하 예방시설", "", "SAFETY_BLOCK", "안전블록"],
  ["추락·낙하 예방시설", "", "DANGER_AREA_BARRIER", "위험구역 차단시설"],
  ["안전표지 및 통제시설", "", "SAFETY_SIGN", "안전표지판"],
  ["안전표지 및 통제시설", "", "WARNING_SIGN", "경고표지"],
  ["안전표지 및 통제시설", "", "TRAFFIC_CONE", "라바콘"],
  ["안전표지 및 통제시설", "", "SAFETY_FENCE", "안전휀스"],
  ["안전표지 및 통제시설", "", "BARRICADE", "바리케이드"],
  ["안전표지 및 통제시설", "", "ACCESS_CONTROL_FACILITY", "출입통제시설"],
  ["안전표지 및 통제시설", "", "WARNING_LIGHT", "경광등"],
  ["안전표지 및 통제시설", "", "SIGNAL_BATON", "신호봉"],
  ["안전표지 및 통제시설", "", "BARRIER_TAPE", "안전띠(차단테이프)"],
  ["안전점검·계측장비", "", "GAS_DETECTOR", "가스측정기"],
  ["안전점검·계측장비", "", "OXYGEN_METER", "산소농도측정기"],
  ["안전점검·계측장비", "", "NOISE_METER", "소음측정기"],
  ["안전점검·계측장비", "", "LIGHT_METER", "조도측정기"],
  ["안전점검·계측장비", "", "ANEMOMETER", "풍속계"],
  ["안전점검·계측장비", "", "DUST_METER", "분진측정기"],
  ["안전점검·계측장비", "", "VIBRATION_METER", "진동측정기"],
  ["안전점검·계측장비", "", "THERMAL_CAMERA_INSPECTION", "열화상카메라(안전점검용)"],
  ["보건관리", "", "FIRST_AID_KIT", "구급함"],
  ["보건관리", "", "FIRST_AID_SUPPLIES", "응급처치용품"],
  ["보건관리", "", "AED", "자동심장충격기(AED)"],
  ["보건관리", "", "EYEWASH_STATION", "세안기"],
  ["보건관리", "", "HEAT_COLD_PREVENTION_SUPPLIES", "냉·온열질환 예방물품"],
  ["보건관리", "", "VENTILATION_EQUIPMENT", "환기설비(유해작업용)"],
  ["스마트 안전장비", "스마트 개인보호구(PPE)", "SMART_SAFETY_HELMET", "스마트 안전모"],
  ["스마트 안전장비", "스마트 개인보호구(PPE)", "SMART_SAFETY_VEST", "스마트 안전조끼"],
  ["스마트 안전장비", "스마트 개인보호구(PPE)", "SMART_SAFETY_HARNESS", "스마트 안전대"],
  ["스마트 안전장비", "스마트 개인보호구(PPE)", "SMART_WATCH", "스마트워치(심박·SOS·낙상감지)"],
  ["스마트 안전장비", "스마트 개인보호구(PPE)", "SMART_GAS_DETECTOR", "스마트 가스감지기"],
  ["스마트 안전장비", "AI·스마트 CCTV", "SMART_CCTV_AI_VIDEO_ANALYTICS", "AI 영상분석"],
  ["스마트 안전장비", "AI·스마트 CCTV", "SMART_CCTV_AI_SAFETY_MANAGEMENT", "AI 안전관리 CCTV"],
  ["스마트 안전장비", "AI·스마트 CCTV", "SMART_CCTV_AI_HELMET_DETECTION", "AI 안전모 착용 인식 CCTV"],
  ["스마트 안전장비", "AI·스마트 CCTV", "SMART_CCTV_AI_VEST_DETECTION", "AI 안전조끼 착용 인식 CCTV"],
  ["스마트 안전장비", "AI·스마트 CCTV", "SMART_CCTV_AI_DANGER_ZONE_INTRUSION", "AI 위험구역 침입감지 CCTV"],
  ["스마트 안전장비", "AI·스마트 CCTV", "SMART_CCTV_AI_FALL_RISK_DETECTION", "AI 추락위험 감지 CCTV"],
  ["스마트 안전장비", "AI·스마트 CCTV", "SMART_CCTV_AI_FALLEN_WORKER_DETECTION", "AI 쓰러짐(낙상) 감지 CCTV"],
  ["스마트 안전장비", "AI·스마트 CCTV", "SMART_CCTV_AI_FIRE_SMOKE_DETECTION", "AI 화재·연기 감지 CCTV"],
  ["스마트 안전장비", "AI·스마트 CCTV", "SMART_CCTV_GENERAL_SPECIAL", "일반·특수 CCTV"],
  ["스마트 안전장비", "AI·스마트 CCTV", "SMART_CCTV_MOBILE", "이동식 CCTV"],
  ["스마트 안전장비", "AI·스마트 CCTV", "SMART_CCTV_SOLAR_MOBILE", "태양광 이동형 CCTV"],
  ["스마트 안전장비", "AI·스마트 CCTV", "SMART_CCTV_PTZ", "PTZ(회전형) 안전감시 CCTV"],
  ["스마트 안전장비", "AI·스마트 CCTV", "SMART_CCTV_THERMAL", "열화상 CCTV"],
  ["스마트 안전장비", "AI·스마트 CCTV", "SMART_CCTV_DUAL_SPECTRUM", "듀얼스펙트럼(열화상+광학) CCTV"],
  ["스마트 안전장비", "작업자 안전관리", "WORKER_LOCATION_ACCESS_MANAGEMENT", "위치·출입 관리"],
  ["스마트 안전장비", "작업자 안전관리", "WORKER_LOCATION_TRACKING", "작업자 위치추적(UWB·BLE·RFID)"],
  ["스마트 안전장비", "작업자 안전관리", "WORKER_ACCESS_CONTROL", "출입관리 시스템"],
  ["스마트 안전장비", "작업자 안전관리", "WORKER_ELECTRONIC_ACCESS_CONTROL", "전자출입관리 시스템"],
  ["스마트 안전장비", "작업자 안전관리", "WORKER_SOS_EMERGENCY_CALL", "SOS 비상호출 시스템"],
  ["스마트 안전장비", "중장비 안전관리", "HEAVY_EQUIPMENT_PROXIMITY_ALARM", "중장비 접근경보장치"],
  ["스마트 안전장비", "중장비 안전관리", "HEAVY_EQUIPMENT_COLLISION_PREVENTION", "충돌방지장치"],
  ["스마트 안전장비", "중장비 안전관리", "HEAVY_EQUIPMENT_REAR_DETECTOR", "후방감지장치"],
  ["스마트 안전장비", "중장비 안전관리", "HEAVY_EQUIPMENT_PINCH_PREVENTION", "협착방지장치"],
  ["스마트 안전장비", "중장비 안전관리", "CRANE_PROXIMITY_ALARM", "크레인 접근경보장치"],
  ["스마트 안전장비", "구조물·추락 안전관리", "OPENING_PROXIMITY_ALARM", "개구부 접근경보장치"],
  ["스마트 안전장비", "구조물·추락 안전관리", "FALL_DETECTION_SYSTEM", "추락감지 시스템"],
  ["스마트 안전장비", "구조물·추락 안전관리", "SCAFFOLD_DISPLACEMENT_MONITORING", "비계 변위 모니터링"],
  ["스마트 안전장비", "구조물·추락 안전관리", "RETAINING_WALL_MEASUREMENT_SYSTEM", "흙막이 계측 시스템"],
  ["스마트 안전장비", "작업환경 모니터링(IoT)", "IOT_GAS_DETECTOR", "IoT 가스감지기"],
  ["스마트 안전장비", "작업환경 모니터링(IoT)", "IOT_DUST_METER", "IoT 분진측정기"],
  ["스마트 안전장비", "작업환경 모니터링(IoT)", "IOT_NOISE_METER", "IoT 소음측정기"],
  ["스마트 안전장비", "작업환경 모니터링(IoT)", "IOT_TEMPERATURE_HUMIDITY_METER", "IoT 온·습도측정기"],
  ["스마트 안전장비", "작업환경 모니터링(IoT)", "IOT_ANEMOMETER", "IoT 풍속계"],
] as const;

export type ProductCategoryCode = (typeof PRODUCT_CATEGORIES)[number][2];

export const FEATURED_CATEGORIES = [
  "PPE_SAFETY_HELMET",
  "PPE_SAFETY_SHOES",
  "PPE_HIGH_VISIBILITY_VEST",
  "PPE_SAFETY_GLASSES",
  "FALL_PREVENTION_NET",
  "SMART_CCTV_AI_HELMET_DETECTION",
] satisfies ProductCategoryCode[];

export function categoryLabel(code: string) {
  return PRODUCT_CATEGORIES.find((category) => category[2] === code)?.[3] ?? code;
}

export function categoryPath(code: string) {
  const category = PRODUCT_CATEGORIES.find((item) => item[2] === code);
  if (!category) return code;
  return [category[0], category[1], category[3]].filter(Boolean).join(" > ");
}
