package com.dropshipshop.api.fulfillment.domain;

public enum FulfillmentHandoverReasonCode {
	ADMIN_TAKEOVER,
	PII_CUTOFF_REACHED,
	PORTAL_SUSPENDED,
	PORTAL_DISABLED,
	MANAGER_DISCONNECTED,
	CONTACT_EMAIL_CHANGED,
	CONTRACT_EXPIRED,
	CONTRACT_REVOKED,
	SUPPLIER_SHORTAGE_REPORTED,
	TERMINAL_STATE
}
